// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxze1NxoHsYJ2fFmqramYx-Hwi4pBsCEA',
    appId: '1:607716932889:web:b86bed476afccba307d988',
    messagingSenderId: '607716932889',
    projectId: 'flutter-randunite',
    authDomain: 'flutter-randunite.firebaseapp.com',
    storageBucket: 'flutter-randunite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqXdaALK-w145-iCjFsX3aaW4_f8ILQJc',
    appId: '1:607716932889:android:b313caf20c134f5f07d988',
    messagingSenderId: '607716932889',
    projectId: 'flutter-randunite',
    storageBucket: 'flutter-randunite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAJVeSUHv751y1UM-A-MdAA3V9U-AbaWs',
    appId: '1:607716932889:ios:ab9f213bd52ae27207d988',
    messagingSenderId: '607716932889',
    projectId: 'flutter-randunite',
    storageBucket: 'flutter-randunite.firebasestorage.app',
    iosBundleId: 'com.example.pokehomy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAJVeSUHv751y1UM-A-MdAA3V9U-AbaWs',
    appId: '1:607716932889:ios:ab9f213bd52ae27207d988',
    messagingSenderId: '607716932889',
    projectId: 'flutter-randunite',
    storageBucket: 'flutter-randunite.firebasestorage.app',
    iosBundleId: 'com.example.pokehomy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL3NR-ftmGvRJQWewbXPEEGAWWlPzCvuY',
    appId: '1:607716932889:web:c24cbd1a24bac2f307d988',
    messagingSenderId: '607716932889',
    projectId: 'flutter-randunite',
    authDomain: 'flutter-randunite.firebaseapp.com',
    storageBucket: 'flutter-randunite.firebasestorage.app',
  );
}
